name: Create 100 contributions

on:
  workflow_dispatch:

jobs:
  create_100_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "SajatFelhasznaloNeved"    # Itt add meg a GitHub felhasználóneved
          git config user.email "email@példád.hu"         # Fontos, hogy olyan mail legyen, amit a GitHub-fiókodhoz verifikáltál!

      - name: Make 100 commits
        run: |
          # Hozunk létre egy fájlt, amibe minden commitnál írunk valamit
          touch commits.txt
          for i in $(seq 1 100)
          do
            # A dátumot pl. i nappal ezelőttre állítjuk (így szétszórva a commitokat)
            # Ha mind a 100-at ugyanarra a napra akarod, elhagyhatod a 'date -d...' részt.
            COMMIT_DATE=$(date -d "$i days ago" "+%Y-%m-%dT%H:%M:%S")

            echo "Commit #$i at $COMMIT_DATE" >> commits.txt
            git add commits.txt

            # A commit során beállítjuk a dátumot
            GIT_AUTHOR_DATE="$COMMIT_DATE" \
            GIT_COMMITTER_DATE="$COMMIT_DATE" \
            git commit -m "Fake commit #$i at $COMMIT_DATE"
          done

      - name: Push changes
        run: |
          # A HEAD:main feltételezi, hogy a main branch-re akarsz push-olni
          # Ha ez védett, akkor lehet, hogy egy másik branch-re kell pusholnod, majd PR-t nyitnod
          git push origin HEAD:main
        env:
          # Ezzel alapból a GITHUB_TOKEN-t fogja használni a push-hoz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
