name: Create 100 contributions

on:
  workflow_dispatch:

jobs:
  create_100_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "andrijajovanovic98" 
          git config user.email "andrija.jovanovic1998@gmail.com"

      - name: Switch to main branch and rebase
        run: |
          # Biztos, ami biztos, ráállunk a main branch-re
          git checkout main
          # Lehúzzuk a változásokat és rebase-el integráljuk
          git pull --rebase origin main

      - name: Make 100 commits
        run: |
          # Hozunk létre vagy frissítünk egy fájlt, amibe minden commitnál írunk valamit
          touch commits.txt
          for i in $(seq 1 100)
          do
            COMMIT_DATE=$(date -d "$i days ago" "+%Y-%m-%dT%H:%M:%S")
            
            echo "Commit #$i at $COMMIT_DATE" >> commits.txt
            git add commits.txt
            
            GIT_AUTHOR_DATE="$COMMIT_DATE" \
            GIT_COMMITTER_DATE="$COMMIT_DATE" \
            git commit -m "Fake commit #$i at $COMMIT_DATE"
          done

      - name: Push changes
        run: |
          # Közvetlenül push-olunk a main branch-re
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
