name: Create 100 contributions

on:
  workflow_dispatch:

jobs:
  create_100_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "andrijajovanovic98" 
          git config user.email "andrija.jovanovic1998@gmail.com"

      - name: Fetch latest changes and create a new branch
        run: |
          git checkout main
          git pull origin main
          # Új branch létrehozása az egyedi commitokhoz
          BRANCH_NAME="fake-contributions-$(date +%s)"
          git checkout -b $BRANCH_NAME

      - name: Make 100 commits
        run: |
          touch commits.txt
          for i in $(seq 1 100)
          do
            COMMIT_DATE=$(date -d "$i days ago" "+%Y-%m-%dT%H:%M:%S")
            
            echo "Commit #$i at $COMMIT_DATE" >> commits.txt
            git add commits.txt
            
            GIT_AUTHOR_DATE="$COMMIT_DATE" \
            GIT_COMMITTER_DATE="$COMMIT_DATE" \
            git commit -m "Fake commit #$i at $COMMIT_DATE"
          done

      - name: Push changes to new branch
        run: |
          git push origin HEAD:$BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          gh pr create --base main --head $BRANCH_NAME --title "Fake contributions" --body "This PR contains 100 fake commits."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
