name: Create full year contributions

on:
  workflow_dispatch:

jobs:
  create_commits_for_year:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "andrijajovanovic98"
          git config user.email "andrija.jovanovic1998@gmail.com"

      - name: Make commits for each day
        run: |
          # Létrehozunk egy commits.txt fájlt,
          # hogy legyen mit commitolni.
          touch commits.txt

          # 365 napra visszamenőleg (1 év), 1 commit / nap.
          for i in $(seq 365 -1 1)
          do
            # A commit dátuma i nappal ezelőtti napra kerül 12:00:00 időponttal.
            COMMIT_DATE=$(date -d "$i days ago" +"%Y-%m-%dT12:00:00")
            
            echo "Commit for day $i ($COMMIT_DATE)" >> commits.txt
            git add commits.txt

            # Az AUTHOR_DATE és COMMITTER_DATE környezeti változókkal
            # állítjuk be a commit dátumát.
            GIT_AUTHOR_DATE="$COMMIT_DATE" \
            GIT_COMMITTER_DATE="$COMMIT_DATE" \
            git commit -m "Day-$i commit at $COMMIT_DATE"
          done

      - name: Pull (rebase) from origin/main
        run: |
          # Ha a main branch az alapértelmezett, ezzel felvesszük a legfrissebb változásokat.
          git pull --rebase origin main

      - name: Push changes
        run: |
          # Feltöltés a main branch-re. 
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
