name: Create 100 contributions

on:
  workflow_dispatch:

jobs:
  create_100_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "andrijajovanovic98"    # Itt add meg a GitHub felhasználóneved
          git config user.email "andrija.jovanovic1998@gmail.com"         # Fontos, hogy olyan mail legyen, amit a GitHub-fiókodhoz verifikáltál!

      - name: Make 100 commits
        run: |
          # Hozunk létre egy fájlt, amibe minden commitnál írunk valamit
          touch commits.txt
          for i in $(seq 1 100)
          for i in $(seq 365 -1 1)  # 365-től lefelé 1-ig
          do
            COMMIT_DATE=$(date -d "$i days ago" +"%Y-%m-%dT12:00:00")
            echo "Commit for day $i ($COMMIT_DATE)" >> commits.txt
            git add commits.txt
            
            GIT_AUTHOR_DATE="$COMMIT_DATE" \
            GIT_COMMITTER_DATE="$COMMIT_DATE" \
            git commit -m "Day-$i commit at $COMMIT_DATE"
          done

      - name: Push changes
        run: |
          # A HEAD:main feltételezi, hogy a main branch-re akarsz push-olni
          # Ha ez védett, akkor lehet, hogy egy másik branch-re kell pusholnod, majd PR-t nyitnod
          git push origin HEAD:main
        env:
          # Ezzel alapból a GITHUB_TOKEN-t fogja használni a push-hoz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
