name: Create full year contributions

on:
  workflow_dispatch:

jobs:
  create_commits_for_year:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "andrijajovanovic98"
          git config user.email "andrija.jovanovic1998@gmail.com"

      - name: Make commits for each day
        run: |
          touch commits.txt
          # 365 napra visszamenően (1 év)
          # Ha 1 commitot szeretnél minden napra, használhatsz pl:
          for i in $(seq 365 -1 1)  # 365-től lefelé 1-ig
          do
            COMMIT_DATE=$(date -d "$i days ago" +"%Y-%m-%dT12:00:00")
            echo "Commit for day $i ($COMMIT_DATE)" >> commits.txt
            git add commits.txt
            
            GIT_AUTHOR_DATE="$COMMIT_DATE" \
            GIT_COMMITTER_DATE="$COMMIT_DATE" \
            git commit -m "Day-$i commit at $COMMIT_DATE"
          done

      - name: Push changes
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
