name: Create full year contributions

on:
  workflow_dispatch:

jobs:
  create_commits_for_year:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "andrijajovanovic98"
          git config user.email "andrija.jovanovic1998@gmail.com"

      - name: Make commits for each day
        run: |
          # Létrehozzuk a commits.txt fájlt
          touch commits.txt

          # 365 napra visszamenőleg, mindegyik naphoz 1 commit
          for i in $(seq 365 -1 1)
          do
            COMMIT_DATE=$(date -d "$i days ago" +"%Y-%m-%dT12:00:00")
            echo "Commit for day $i ($COMMIT_DATE)" >> commits.txt
            git add commits.txt

            # A commit szerző és committer dátuma is a visszadátumozott idő
            GIT_AUTHOR_DATE="$COMMIT_DATE" \
            GIT_COMMITTER_DATE="$COMMIT_DATE" \
            git commit -m "Day-$i commit at $COMMIT_DATE"
          done

      - name: Push to new branch
        run: |
          # Egy új branchre pusholunk, pl. fake-year-commits
          git push origin HEAD:fake-year-commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Ez az az ág, ahova az imént pusholtunk
          branch: fake-year-commits
          # Ez pedig a cél ág
          base: main
          title: "Fake daily commits for last year"
          body: "Generate commits for each day of the past year"
          commit-message: "Add daily commits"
